CREATE TABLE login_request (
	id INT(11) NOT NULL AUTO_INCREMENT,
	user_id INT(11) NOT NULL,
	valid_until DATETIME NULL DEFAULT NULL,
	code CHAR(8) NULL DEFAULT NULL,
	created_time DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
	created_by VARCHAR(100) NULL DEFAULT 'system',
	updated_time DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	updated_by VARCHAR(100) NULL DEFAULT 'system',
	PRIMARY KEY (id)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;